/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/calculate/light": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 라이트 모드 저축여력 추정 및 4대 성향 유형 분류 */
        post: operations["calculate_light_api_v1_calculate_light_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/{config_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 설정 데이터 조회 */
        get: operations["get_config_api_v1_config__config_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deep/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 딥 모드 가치관 질문 목록 조회 */
        get: operations["get_deep_questions_api_v1_deep_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 초대 코드 유효성 확인 및 공개 초대 미리보기 조회 */
        get: operations["get_invitation_api_v1_invitations__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{code}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 초대 수락 및 세션 참여 (쿠키 발급) */
        post: operations["join_invitation_api_v1_invitations__code__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/light/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 라이트 모드 5대 질문 및 선택지 목록 조회 */
        get: operations["get_light_questions_api_v1_light_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 참여자 쿠키 기준 활성 세션 조회 */
        get: operations["get_my_session_api_v1_me_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 진단 세션 생성 및 참여자 쿠키 발급 */
        post: operations["create_session_api_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/me/input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 세션 내 본인 임시 저장 답변 조회 */
        get: operations["get_my_input_api_v1_sessions__session_id__me_input_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 세션 내 본인 답변 임시 저장 (진행 중 자동 저장) */
        patch: operations["save_my_input_api_v1_sessions__session_id__me_input_patch"];
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/me/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 세션 내 본인 답변 최종 제출 */
        post: operations["submit_my_input_api_v1_sessions__session_id__me_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/nudge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 미제출 상대방에게 넛지(재촉 알림) 요청 */
        post: operations["nudge_partner_api_v1_sessions__session_id__nudge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 세션 진단 결과 조회 (Discriminated Union: waiting vs ready) */
        get: operations["get_session_result_api_v1_sessions__session_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 세션 진행 및 양측 제출 현황 조회 */
        get: operations["get_session_status_api_v1_sessions__session_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/validate/input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 입력 데이터 이상치 및 재무 상태 유효성 검증 */
        post: operations["validate_user_input_api_v1_validate_input_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 서버 및 데이터베이스 연결 상태 확인 */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConfigResponse */
        ConfigResponse: {
            /**
             * Data
             * @description 설정 데이터 객체
             */
            data: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @description 처리 상태
             * @default success
             * @example success
             */
            status: string;
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /**
             * Mode
             * @description 진단 모드 (light | deep)
             * @default light
             * @example light
             */
            mode: string;
            /**
             * Nickname
             * @description 작성자 닉네임
             * @example 예랑이
             */
            nickname: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /**
             * Code
             * @description 오류 식별 코드
             * @example QUESTION_SET_NOT_FOUND
             */
            code: string;
            /**
             * Fielderrors
             * @description 필드별 유효성 검증 오류 맵 (선택적)
             * @example {}
             */
            fieldErrors?: {
                [key: string]: string[];
            };
            /**
             * Message
             * @description 오류 상세 메시지
             * @example 요청한 버전의 질문 세트를 찾을 수 없습니다.
             */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** @description 오류 세부 정보 객체 */
            error: components["schemas"]["ErrorDetail"];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Database
             * @description 데이터베이스 연결 상태
             * @example connected
             */
            database: string;
            /**
             * Message
             * @description 상태 안내 메시지
             * @example 미리살림 백엔드 서버 및 데이터베이스가 정상 가동 중입니다.
             */
            message?: string | null;
            /**
             * Status
             * @description 서버 상태
             * @example ok
             */
            status: string;
        };
        /** InputValidationRequest */
        InputValidationRequest: {
            /**
             * Debttotal
             * @description 총 부채 잔액 (단위: 만원)
             * @example 5000
             */
            debtTotal?: number | null;
            /**
             * Monthlynetincome
             * @description 월 실수령 순소득 (단위: 만원)
             * @example 350
             */
            monthlyNetIncome?: number | null;
            /**
             * Savings
             * @description 현재 모아둔 저축/예금액 (단위: 만원)
             * @example 3000
             */
            savings?: number | null;
            /**
             * Totalexpense
             * @description 월 총 지출 합계 (단위: 만원)
             * @example 250
             */
            totalExpense?: number | null;
            /**
             * Variableexpenses
             * @description 월 변동 생활비 (단위: 만원)
             * @example 100
             */
            variableExpenses?: number | null;
        };
        /** InputValidationResponse */
        InputValidationResponse: {
            /**
             * Status
             * @description 처리 상태
             * @default success
             * @example success
             */
            status: string;
            /**
             * Warnings
             * @description 검증 규칙에 따른 경고 및 확인 목록
             */
            warnings?: components["schemas"]["ValidationWarningItem"][];
        };
        /** InvitationResponse */
        InvitationResponse: {
            /**
             * Duration
             * @description 예상 소요 시간
             * @example 3분
             */
            duration: string;
            /**
             * Expiresat
             * @description 초대장 만료 일시 (ISO 8601)
             * @example 2026-08-19T12:00:00Z
             */
            expiresAt: string;
            /**
             * Mode
             * @description 진단 모드 (light | deep)
             * @example light
             */
            mode: string;
        };
        /** JoinInvitationRequest */
        JoinInvitationRequest: {
            /**
             * Nickname
             * @description 참여자 닉네임
             * @example 예신이
             */
            nickname: string;
        };
        /** LightComparisonResultData */
        LightComparisonResultData: {
            /**
             * Discussiontopics
             * @description 대화해 볼 중립적인 주제 목록
             * @example [
             *       "월 고정비와 자유 사용 경비의 기준 나누기",
             *       "비상금 관리 방식 정하기"
             *     ]
             */
            discussionTopics?: string[];
            /**
             * Mutualhitcount
             * @description 양측 상호 예측 적중 개수
             * @example 3
             */
            mutualHitCount: number;
            /** @description 본인의 성향 유형 분류 결과 */
            myType: components["schemas"]["TypeClassificationResult"];
            /** @description 상대방의 성향 유형 분류 결과 */
            partnerType: components["schemas"]["TypeClassificationResult"];
            /**
             * Questioncount
             * @description 전체 질문 수
             * @example 5
             */
            questionCount: number;
            /**
             * Questions
             * @description 공개 가능한 질문별 양측 비교 및 적중 목록
             */
            questions: components["schemas"]["QuestionComparisonItem"][];
            /**
             * Tagline
             * @description 중립적인 결과 태그라인
             * @example 서로의 생각을 이해하고 맞춰가는 첫걸음
             */
            tagline: string;
        };
        /** LightDiagnosisRequest */
        LightDiagnosisRequest: {
            /**
             * Incomea
             * @description 본인이 선택한 월 실수령 소득 구간 대표값 (단위: 만원/월)
             * @example 250
             */
            incomeA: number;
            /**
             * Incomeb
             * @description 상대방이 선택한 월 실수령 소득 구간 대표값 (단위: 만원/월, 미입력/외벌이 시 0)
             * @default 0
             * @example 250
             */
            incomeB: number;
            /**
             * Mgmtaxisanswers
             * @description 관리축 성향 문항 점수(1~5점) 또는 선택지 인덱스/코드 리스트
             * @example [
             *       2
             *     ]
             */
            mgmtAxisAnswers: number[] | number[] | string[] | number[][] | number[][];
            /**
             * Surplusa
             * @description 본인이 선택한 월 잉여자금 구간 대표값 (단위: 만원/월)
             * @example 85
             */
            surplusA: number;
            /**
             * Surplusb
             * @description 상대방이 선택한 월 잉여자금 구간 대표값 (단위: 만원/월, 미입력/외벌이 시 0)
             * @default 0
             * @example 40
             */
            surplusB: number;
            /**
             * Timeaxisanswers
             * @description 시간축 성향 문항 점수(1~5점) 또는 선택지 인덱스/코드 리스트
             * @example [
             *       2
             *     ]
             */
            timeAxisAnswers: number[] | number[] | string[];
        };
        /** LightDiagnosisResponse */
        LightDiagnosisResponse: {
            /** @description 라이트 진단 결과 데이터 */
            result: components["schemas"]["LightDiagnosisResultData"];
            /**
             * Status
             * @description 처리 상태
             * @default success
             * @example success
             */
            status: string;
        };
        /** LightDiagnosisResultData */
        LightDiagnosisResultData: {
            /** @description 저축여력 연산 결과 */
            surplus: components["schemas"]["SurplusResult"];
            /** @description 성향 유형 분류 결과 */
            typeClassification: components["schemas"]["TypeClassificationResult"];
        };
        /** NudgeResponse */
        NudgeResponse: {
            /**
             * Message
             * @description 결과 안내 메시지
             * @default 상대방에게 참여 알림을 전송했습니다.
             * @example 상대방에게 참여 알림을 전송했습니다.
             */
            message: string;
            /**
             * Status
             * @description 처리 상태
             * @default success
             * @example success
             */
            status: string;
        };
        /** QuestionComparisonItem */
        QuestionComparisonItem: {
            /**
             * Ishit
             * @description 현재 사용자 관점의 상대방 예측 적중 여부 (myGuess == partnerAnswer)
             * @example true
             */
            isHit: boolean;
            /**
             * Ismatch
             * @description 질문별 본인과 상대방의 답변 일치 여부 (myAnswer == partnerAnswer)
             * @example true
             */
            isMatch: boolean;
            /**
             * Myanswer
             * @description 본인 공개 답변 인덱스 (0|1|2|3|null)
             * @example 2
             */
            myAnswer: (0 | 1 | 2 | 3) | null;
            /**
             * Myanswerlabel
             * @description 본인 답변 선택지 라벨
             * @example 저축 약간 우선
             */
            myAnswerLabel?: string | null;
            /**
             * Myguess
             * @description 내가 예측한 상대방 답변 인덱스 (0|1|2|3|null)
             * @example 2
             */
            myGuess?: (0 | 1 | 2 | 3) | null;
            /**
             * Partneranswer
             * @description 상대방 공개 답변 인덱스 (0|1|2|3|null)
             * @example 2
             */
            partnerAnswer: (0 | 1 | 2 | 3) | null;
            /**
             * Partneranswerlabel
             * @description 상대방 답변 선택지 라벨
             * @example 저축 약간 우선
             */
            partnerAnswerLabel?: string | null;
            /**
             * Questionid
             * @description 공개 가능한 질문 고유 식별자 ID
             * @example spending_style
             * @enum {string}
             */
            questionId: "spending_style" | "shared_expense";
            /**
             * Questiontext
             * @description 질문 본문 문구
             * @example 소비 및 저축 성향
             */
            questionText: string;
        };
        /** QuestionItem */
        QuestionItem: {
            /**
             * Category
             * @description 질문 카테고리 (소득 | 잉여자금 | 시간축 성향 | 부채 | 관리축 성향 | 가치관)
             * @example 소득
             */
            category: string;
            /**
             * Id
             * @description 질문 고유 식별자 ID
             * @example monthly_income
             */
            id: string;
            /**
             * Options
             * @description 선택적 보기(옵션) 목록
             */
            options?: components["schemas"]["QuestionOption"][] | null;
            /**
             * Order
             * @description 질문 표시 순서
             * @example 1
             */
            order: number;
            /** @description 척도 문항 설정 및 단계별 보기 */
            scaleConfig?: components["schemas"]["ScaleConfig"] | null;
            /**
             * Subtext
             * @description 질문 보조/안내 문구
             * @example 세후 실수령액(월급 기준)을 선택해 주세요.
             */
            subText?: string | null;
            /**
             * Target
             * @description 답변 대상자 (self: 본인, partner: 배우자/상대방)
             * @default self
             * @example self
             */
            target: string;
            /**
             * Text
             * @description 질문 본문 문구
             * @example 본인의 월 실수령 소득 구간을 선택해 주세요.
             */
            text: string;
            /**
             * Type
             * @description 문항 유형 (single_choice | range_choice | scale)
             * @example range_choice
             */
            type: string;
        };
        /** QuestionOption */
        QuestionOption: {
            /**
             * Description
             * @description 선택지 부가 설명
             * @example 월 실수령 200만원 이상 ~ 300만원 미만
             */
            description?: string | null;
            /**
             * Label
             * @description 선택지 표시 라벨 문구
             * @example 200~300만원
             */
            label: string;
            /**
             * Rep
             * @description 구간 대표값 (만원 단위 또는 척도 점수)
             * @example 250
             */
            rep?: number | null;
            /**
             * Value
             * @description 선택지 고유 식별값
             * @example 200_300
             */
            value: string | number;
        };
        /** QuestionSet */
        QuestionSet: {
            /**
             * Description
             * @description 질문 세트 설명
             * @example 3분 만에 확인하는 신혼부부 맞춤형 저축여력 추정 및 4대 재무 성향 진단 5대 문항입니다.
             */
            description: string;
            /**
             * Questions
             * @description 질문 및 선택지 목록
             */
            questions: components["schemas"]["QuestionItem"][];
            /**
             * Title
             * @description 질문 세트 제목
             * @example 미리살림 라이트 진단 질문 세트
             */
            title: string;
            /**
             * Version
             * @description 질문 세트 버전 식별자
             * @example light-v1
             */
            version: string;
        };
        /** ResultReadyResponse */
        ResultReadyResponse: {
            /**
             * Partnercompleted
             * @description 상대방 완료 여부 (항상 True)
             * @constant
             */
            partnerCompleted: true;
            /** @description 양측 비교 결과 데이터 (금액 정보 제외) */
            result: components["schemas"]["LightComparisonResultData"];
            /**
             * @description 결과 준비 완료 상태 식별자 (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            status: "ready";
        };
        /** ResultWaitingResponse */
        ResultWaitingResponse: {
            /**
             * Partnercompleted
             * @description 상대방 완료 여부 (항상 False)
             * @constant
             */
            partnerCompleted: false;
            /**
             * @description 결과 대기 상태 식별자 (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            status: "waiting";
        };
        /** SaveInputRequest */
        SaveInputRequest: {
            /**
             * Answers
             * @description 본인 질문별 답변 인덱스 리스트 (0|1|2|3|null)
             * @example [
             *       0,
             *       1,
             *       null,
             *       3
             *     ]
             */
            answers: ((0 | 1 | 2 | 3) | null)[];
            /**
             * Guesses
             * @description 상대방 질문별 예측 인덱스 리스트 (0|1|2|3|null)
             * @example [
             *       1,
             *       1,
             *       2,
             *       null
             *     ]
             */
            guesses?: ((0 | 1 | 2 | 3) | null)[] | null;
        };
        /** ScaleConfig */
        ScaleConfig: {
            /**
             * Leftlabel
             * @description 왼쪽(1점) 척도 기준 문구
             * @example 현재의 소비와 즐거움을 우선
             */
            leftLabel: string;
            /**
             * Max
             * @description 척도 최대 점수
             * @default 5
             * @example 5
             */
            max: number;
            /**
             * Min
             * @description 척도 최소 점수
             * @default 1
             * @example 1
             */
            min: number;
            /**
             * Rightlabel
             * @description 오른쪽(5점) 척도 기준 문구
             * @example 미래의 저축과 안정을 우선
             */
            rightLabel: string;
            /**
             * Steps
             * @description 1~5점 각 단계별 선택 문구
             * @example [
             *       "1점: 매우 소비 우선",
             *       "2점: 소비 약간 우선",
             *       "3점: 균형",
             *       "4점: 저축 약간 우선",
             *       "5점: 매우 저축 우선"
             *     ]
             */
            steps?: string[] | null;
        };
        /** SessionParticipant */
        SessionParticipant: {
            /**
             * Hassubmitted
             * @description 답변 제출 완료 여부
             * @default false
             * @example false
             */
            hasSubmitted: boolean;
            /**
             * Nickname
             * @description 참여자 닉네임
             * @example 예랑이
             */
            nickname: string;
            /**
             * Role
             * @description 참여자 역할 (creator | invitee)
             * @example creator
             */
            role: string;
        };
        /** SessionResponse */
        SessionResponse: {
            /**
             * Createdat
             * @description 세션 생성 일시 (ISO 8601)
             * @example 2026-08-12T12:00:00Z
             */
            createdAt: string;
            /**
             * Id
             * @description 세션 고유 ID
             * @example sess_8f3a9b2c
             */
            id: string;
            /**
             * Invitationcode
             * @description 상대방 초대용 코드
             * @example INV-7890
             */
            invitationCode: string;
            /**
             * Mode
             * @description 진단 모드
             * @default light
             * @example light
             */
            mode: string;
            /**
             * Myrole
             * @description 현재 사용자의 역할 (creator | invitee)
             * @default creator
             * @example creator
             */
            myRole: string;
            /**
             * Participants
             * @description 참여자 목록
             */
            participants?: components["schemas"]["SessionParticipant"][];
            /**
             * Status
             * @description 세션 진행 상태 (in_progress | completed | expired)
             * @default in_progress
             * @example in_progress
             */
            status: string;
        };
        /** SessionStatusResponse */
        SessionStatusResponse: {
            /**
             * Expiresat
             * @description 세션 만료 일시 (ISO 8601)
             * @example 2026-08-19T12:00:00Z
             */
            expiresAt: string | null;
            /**
             * Mecompleted
             * @description 내 제출 완료 여부
             * @example true
             */
            meCompleted: boolean;
            /**
             * Partnercompleted
             * @description 상대방 제출 완료 여부
             * @example false
             */
            partnerCompleted: boolean;
            /**
             * Partnerjoined
             * @description 상대방 세션 참여 여부
             * @example true
             */
            partnerJoined: boolean;
            /**
             * Partnernudgedat
             * @description 최근 넛지 알림 전송 일시 (ISO 8601)
             * @example 2026-08-12T12:30:00Z
             */
            partnerNudgedAt: string | null;
        };
        /** SubmitInputRequest */
        SubmitInputRequest: {
            /**
             * Answers
             * @description 본인 질문별 최종 답변 인덱스 리스트 (0|1|2|3|null)
             * @example [
             *       0,
             *       1,
             *       2,
             *       3
             *     ]
             */
            answers: ((0 | 1 | 2 | 3) | null)[];
            /**
             * Guesses
             * @description 상대방 질문별 최종 예측 인덱스 리스트 (0|1|2|3|null)
             * @example [
             *       1,
             *       1,
             *       2,
             *       0
             *     ]
             */
            guesses?: ((0 | 1 | 2 | 3) | null)[] | null;
        };
        /** SurplusResult */
        SurplusResult: {
            /**
             * Caution
             * @description 추정치 주의사항 안내 문구
             * @example ※ 구간 선택 기반 추정치이며, 주거비 변동은 미반영된 금액입니다.
             */
            caution: string;
            /**
             * Formattedsurplus
             * @description 포맷팅된 저축여력 문구
             * @example 약 180만원대
             */
            formattedSurplus: string;
            /**
             * Rawsurplus
             * @description 저축여력 추정 원값 (단위: 만원)
             * @example 181.3
             */
            rawSurplus: number;
            /**
             * Summary
             * @description 저축여력 요약 설명 문구
             * @example 두 분의 합산 예상 월 저축 여력은 약 180만원대입니다.
             */
            summary: string;
        };
        /** TypeClassificationResult */
        TypeClassificationResult: {
            /**
             * Mgmt
             * @description 관리축 성향 코드 (joint | separate)
             * @example joint
             */
            mgmt: string;
            /**
             * Mgmtdescription
             * @description 관리축 성향 상세 설명
             * @example 부부의 소득과 지출을 투명하게 공유하고 하나의 공동 통장으로 함께 관리하는 방식을 선호합니다.
             */
            mgmtDescription: string;
            /**
             * Mgmtlabel
             * @description 관리축 성향 한국어 명칭
             * @example 공동관리형 (통합 관리)
             */
            mgmtLabel: string;
            /**
             * Recommendation
             * @description 신혼부부 맞춤 재무 실천 조언
             * @example 공동의 저축 목표(예: 내 집 마련, 비상금)를 구체적인 금액과 기간으로 설정하고, 정기적으로 재무 현황을 점검해보세요.
             */
            recommendation: string;
            /**
             * Time
             * @description 시간축 성향 코드 (saver | spender)
             * @example saver
             */
            time: string;
            /**
             * Timedescription
             * @description 시간축 성향 상세 설명
             * @example 현재의 소비보다는 미래의 안정과 목표 달성을 위해 저축과 자산 형성을 더 중요하게 생각합니다.
             */
            timeDescription: string;
            /**
             * Timelabel
             * @description 시간축 성향 한국어 명칭
             * @example 미래대비형 (저축 우선)
             */
            timeLabel: string;
            /**
             * Typecode
             * @description 복합 성향 유형 코드 (saver_joint | saver_separate | spender_joint | spender_separate)
             * @example saver_joint
             */
            typeCode: string;
            /**
             * Typedescription
             * @description 복합 성향 유형 상세 해설
             * @example 두 분 모두 미래를 위한 저축을 중시하며, 자금을 함께 모아 공동의 목표를 달성하는 데 최적화된 궁합입니다.
             */
            typeDescription: string;
            /**
             * Typename
             * @description 복합 성향 유형 한국어 명칭
             * @example 함께 모으는 든든한 동반자형
             */
            typeName: string;
        };
        /** UserInputData */
        UserInputData: {
            /**
             * Answers
             * @description 본인 질문별 답변 인덱스 리스트 (0|1|2|3|null)
             * @example [
             *       0,
             *       1,
             *       null,
             *       3
             *     ]
             */
            answers?: ((0 | 1 | 2 | 3) | null)[];
            /**
             * Guesses
             * @description 상대방 질문별 예측 인덱스 리스트 (0|1|2|3|null)
             * @example [
             *       1,
             *       1,
             *       2,
             *       null
             *     ]
             */
            guesses?: ((0 | 1 | 2 | 3) | null)[] | null;
        };
        /** ValidationWarningItem */
        ValidationWarningItem: {
            /**
             * Id
             * @description 검증 규칙 ID (예: V-01, V-02)
             * @example V-01
             */
            id: string;
            /**
             * Level
             * @description 경고 수준 (confirm | warn)
             * @example confirm
             */
            level: string;
            /**
             * Message
             * @description 안내/경고 메시지
             * @example 입력하신 월 소득 금액이 맞는지 다시 한번 확인해 주세요.
             */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    calculate_light_api_v1_calculate_light_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LightDiagnosisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LightDiagnosisResponse"];
                };
            };
            /** @description 입력값 검증 실패 (Validation Error) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_config_api_v1_config__config_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 조회할 설정 데이터 종류 (parameters | coefficients | ranges | benchmarks | light_questions | light_types) */
                config_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description 유효하지 않은 설정 데이터 종류 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 설정 데이터를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력값 검증 실패 (Validation Error) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 서버 내부 / 데이터베이스 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_deep_questions_api_v1_deep_questions_get: {
        parameters: {
            query?: {
                /** @description 딥 진단 질문 세트 버전 (기본값: deep-v1) */
                version?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionSet"];
                };
            };
            /** @description 질문 세트를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력값 검증 실패 (Validation Error) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_invitation_api_v1_invitations__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 초대 코드 (예: INV-7890) */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponse"];
                };
            };
            /** @description 유효하지 않거나 만료된 초대 링크 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력값 검증 실패 (Validation Error) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    join_invitation_api_v1_invitations__code__join_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description 중복 요청 방지를 위한 멱등성 키 (UUID) */
                "Idempotency-Key"?: string | null;
            };
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinInvitationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 존재하지 않거나 만료된 초대 코드 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 이미 상대방이 참여 완료된 세션 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력값 검증 실패 (Validation Error) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_light_questions_api_v1_light_questions_get: {
        parameters: {
            query?: {
                /** @description 질문 세트 버전 식별자 (기본값: light-v1) */
                version?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionSet"];
                };
            };
            /** @description 질문 세트를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력값 검증 실패 (Validation Error) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_my_session_api_v1_me_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description 참여자 인증 쿠키 */
                mrs_participant?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 참여자 인증 쿠키 누락 또는 만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 세션을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력값 검증 실패 (Validation Error) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_session_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description 중복 요청 방지를 위한 멱등성 키 (UUID) */
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 입력값 검증 실패 (Validation Error) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 세션 생성 실패 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_my_input_api_v1_sessions__session_id__me_input_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 세션 ID */
                session_id: string;
            };
            cookie?: {
                mrs_participant?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInputData"];
                };
            };
            /** @description 참여자 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 세션 또는 저장된 입력을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력값 검증 실패 (Validation Error) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    save_my_input_api_v1_sessions__session_id__me_input_patch: {
        parameters: {
            query?: never;
            header?: {
                /** @description 중복 요청 방지를 위한 멱등성 키 (UUID) */
                "Idempotency-Key"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: {
                mrs_participant?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveInputRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInputData"];
                };
            };
            /** @description 참여자 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 이미 제출 완료되어 수정 불가 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력값 검증 실패 (Validation Error) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    submit_my_input_api_v1_sessions__session_id__me_submit_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description 중복 요청 방지를 위한 멱등성 키 (UUID) */
                "Idempotency-Key"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: {
                mrs_participant?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitInputRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatusResponse"];
                };
            };
            /** @description 참여자 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 이미 제출 완료된 상태 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력값 검증 실패 (Validation Error) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    nudge_partner_api_v1_sessions__session_id__nudge_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description 중복 요청 방지를 위한 멱등성 키 (UUID) */
                "Idempotency-Key"?: string | null;
            };
            path: {
                /** @description 세션 ID */
                session_id: string;
            };
            cookie?: {
                mrs_participant?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NudgeResponse"];
                };
            };
            /** @description 참여자 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력값 검증 실패 (Validation Error) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 단시간 내 과도한 알림 요청 제한 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_session_result_api_v1_sessions__session_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 세션 ID */
                session_id: string;
            };
            cookie?: {
                mrs_participant?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultWaitingResponse"] | components["schemas"]["ResultReadyResponse"];
                };
            };
            /** @description 참여자 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 세션을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력값 검증 실패 (Validation Error) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 결과 연산 실패 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_session_status_api_v1_sessions__session_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 세션 ID */
                session_id: string;
            };
            cookie?: {
                mrs_participant?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatusResponse"];
                };
            };
            /** @description 참여자 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 세션을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력값 검증 실패 (Validation Error) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    validate_user_input_api_v1_validate_input_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InputValidationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InputValidationResponse"];
                };
            };
            /** @description 입력값 검증 실패 (Validation Error) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
